# Site settings
title: Nimbicle
email: fjohanns@gmail.com
description: "Musings on software development and management"
baseurl: ""
url: "http://derfsplat.github.io"
twitter_username: derfsplat
github_username:  derfsplat

# Build settings
markdown: kramdown
permalink: pretty

#user defined
#highlighter: rouge
