# Site settings
title: Code Orange
email: fjohanns@gmail.com
description: "Musings on software development and management"
baseurl: ""
url: "http://derfsplat.github.io"
twitter_username: derfsplat
github_username:  derfsplat
site_author: "Fred Johanns III"

# Build settings
markdown: kramdown
permalink: pretty

#user defined
#highlighter: rouge
